{
   "rootElement":{
      "name":{
         "namespaceURI":"test",
         "localPart":"root",
         "prefix":""
      }
   },
   "rules":[
      {
         "headingElement":{
            "name":{
               "namespaceURI":"test",
               "localPart":"root",
               "prefix":""
            }
         },
         "constructs":[
            {
               "name":{
                  "namespaceURI":"test",
                  "localPart":"a",
                  "prefix":""
               }
            }
         ]
      },
      {
         "headingElement":{
            "name":{
               "namespaceURI":"test",
               "localPart":"a",
               "prefix":""
            }
         },
         "constructs":[
            {
               "name":{
                  "namespaceURI":"test",
                  "localPart":"b",
                  "prefix":""
               }
            },
            {
               "name":{
                  "namespaceURI":"test",
                  "localPart":"c",
                  "prefix":""
               }
            }
         ]
      }
   ],
   "name":{
      "namespaceURI":"test",
      "localPart":"test1",
      "prefix":""
   },
   "description":"description"
}