/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package test;

import chrriis.common.UIUtils;
import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import java.awt.BorderLayout;

/**
 *
 * @author lendle
 */
public class TestDJBrowser extends javax.swing.JFrame {
    private JWebBrowser webBrowser=null;
    /**
     * Creates new form TestDJBrowser
     */
    public TestDJBrowser() {
        initComponents();
        this.setSize(800, 600);
        webBrowser = new JWebBrowser();
        webBrowser.navigate("http://www.google.com");
        this.panelBrowser.add(webBrowser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBrowser = new javax.swing.JPanel();
        panelCopntrol = new javax.swing.JPanel();
        buttonTestJavaScript = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBrowser.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelBrowser, java.awt.BorderLayout.CENTER);

        panelCopntrol.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonTestJavaScript.setText("Test JavaScript");
        buttonTestJavaScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTestJavaScriptActionPerformed(evt);
            }
        });
        panelCopntrol.add(buttonTestJavaScript);

        getContentPane().add(panelCopntrol, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTestJavaScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTestJavaScriptActionPerformed
        // TODO add your handling code here:
        webBrowser.executeJavascript("function test1(){alert(2);return 2;}");
        System.out.println(webBrowser.executeJavascriptWithResult("return test1();"));
    }//GEN-LAST:event_buttonTestJavaScriptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestDJBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestDJBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestDJBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestDJBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIUtils.setPreferredLookAndFeel();
        NativeInterface.open();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestDJBrowser().setVisible(true);
            }
        });
        NativeInterface.runEventPump();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTestJavaScript;
    private javax.swing.JPanel panelBrowser;
    private javax.swing.JPanel panelCopntrol;
    // End of variables declaration//GEN-END:variables
}
